### ISSUE TITLE
Error when check email received 

### ISSUE THREAD

**Issue by xseth03** [NETWAYS/check_email#8]
Hi, 

the recipient receives the email but I get this error message when he checks if the email is present.

```
UNKNOWN: Python error: 'NoneType' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "./check_email", line 557, in <module>
    main()
  File "./check_email", line 451, in main
    parsed.cleanup_time)
  File "./check_email", line 160, in search_mail
    email_server_date_as_unix = self.parse_received(raw_email['Received'])
  File "./check_email", line 125, in parse_received
    email_server_date_as_unix))
  File "/usr/lib/python2.7/email/_parseaddr.py", line 154, in mktime_tz
    if data[9] is None:
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by RincewindsHat** [comment]
Hi @xseth03  sorry for the delay, did you try to use the plugin with python2?

**Comment by martialblog** [comment]
From the error we can see that it's likely Python2 `/usr/lib/python2.7/email/_parseaddr.py`

Please use Python3, we haven't tested/developed this Plugin for Python2.
